"""add confirmation

Revision ID: 5233d6ab8136
Revises: be4e30c86262
Create Date: 2016-08-23 14:23:59.382929

"""

# revision identifiers, used by Alembic.
revision = '5233d6ab8136'
down_revision = 'be4e30c86262'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
