"""first migration

Revision ID: 542d65e01f71
Revises: None
Create Date: 2016-08-22 10:36:13.976438

"""

# revision identifiers, used by Alembic.
revision = '542d65e01f71'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
