"""blog migrate2

Revision ID: eea56be07755
Revises: eaa4e3564c0b
Create Date: 2016-08-26 15:05:08.693306

"""

# revision identifiers, used by Alembic.
revision = 'eea56be07755'
down_revision = 'eaa4e3564c0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
